services:
  frontend:
    build: ./Frontend
    container_name: Frontend
    ports:
      - "3000:3000"
    depends_on:
      - Backend
    restart: always

  backend:
    build: ./Backend
    container_name: Backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - Frontend
      - Backend
    restart: always
